name: Package JavaFX App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew (only Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build and package application
        run: ./gradlew jpackage

      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: MonApp-${{ runner.os }}
          path: build/jpackage
